// Writes the checked-in corpus fixtures (tests/corpus/<suite>.jsonl.gz):
// one line per case with FNV-1a hashes of the oracle's SVG and canonical
// semantic record, so `cargo test` can verify parity without Node.
// Usage: node fixtures.mjs <suite>...   (cases are regenerated by cases.mjs)
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { fixtureLine } from "./oracle.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const dest = path.join(here, "..", "..", "tests", "corpus");
fs.mkdirSync(dest, { recursive: true });
for (const suite of process.argv.slice(2)) {
  const cases = execFileSync("node", [path.join(here, "cases.mjs"), suite], { maxBuffer: 1 << 30, encoding: "utf8" })
    .split("\n")
    .filter((l) => l.trim());
  const lines = cases.map((l) => JSON.stringify(fixtureLine(JSON.parse(l))));
  const gz = zlib.gzipSync(Buffer.from(lines.join("\n") + "\n"), { level: 9 });
  fs.writeFileSync(path.join(dest, `${suite}.jsonl.gz`), gz);
  console.error(`${suite}: ${lines.length} cases, ${(gz.length / 1024).toFixed(0)} KiB`);
}
