// Writes the checked-in corpus fixtures (tests/corpus/<suite>.jsonl.gz):
// one line per case with FNV-1a hashes of the oracle's SVG and canonical
// semantic record, so `cargo test` can verify parity without Node.
// Usage: node fixtures.mjs <suite>...   (cases are regenerated by cases.mjs)
//
// Fixtures are canonical for V8 on x64 (the crate's default reference
// platform). On arm64 hosts run this with an x64 Node, e.g. under Rosetta:
//   ORACLE_NODE=/path/to/node-x64/bin/node $ORACLE_NODE tools/oracle/fixtures.mjs …
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { fixtureLine } from "./oracle.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
if (process.arch !== "x64") {
  console.error(`fixtures must be generated by x64 Node (this is ${process.arch}); see the header comment`);
  process.exit(1);
}
const dest = path.join(here, "..", "..", "tests", "corpus");
fs.mkdirSync(dest, { recursive: true });
for (const suite of process.argv.slice(2)) {
  const cases = execFileSync(process.execPath, [path.join(here, "cases.mjs"), suite], { maxBuffer: 1 << 30, encoding: "utf8" })
    .split("\n")
    .filter((l) => l.trim());
  const lines = cases.map((l) => JSON.stringify(fixtureLine(JSON.parse(l))));
  const gz = zlib.gzipSync(Buffer.from(lines.join("\n") + "\n"), { level: 9 });
  fs.writeFileSync(path.join(dest, `${suite}.jsonl.gz`), gz);
  console.error(`${suite}: ${lines.length} cases, ${(gz.length / 1024).toFixed(0)} KiB`);
}
