// Emits Rust source for the extracted upstream tables.
//
// Input:  tools/codegen/out/tables.json, tools/codegen/out/misc.json
// Output: src/generated/*.rs
//
// The generated modules contain only data (no functions); the types they use
// are defined in src/template.rs.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..", "..");
const genDir = path.join(root, "src", "generated");
const tables = JSON.parse(fs.readFileSync(path.join(here, "out", "tables.json"), "utf8"));
const misc = JSON.parse(fs.readFileSync(path.join(here, "out", "misc.json"), "utf8"));
const pin = tables.upstream;

const HEADER = `// @generated by tools/codegen/emit.mjs from milsymbol.js ${pin.version}
// (${pin.upstream} @ ${pin.commit}, MIT, see LICENSE-MIT-milsymbol).
// Regenerate with \`tools/codegen/regenerate.sh\`; do not edit by hand.
`;

// ---------------------------------------------------------------------------
// Rust literal helpers.

function rstr(s) {
  let out = '"';
  for (const ch of s) {
    const c = ch.codePointAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === "\\") out += "\\\\";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
    else out += ch;
  }
  return out + '"';
}

function rf64(n) {
  if (typeof n !== "number" || !Number.isFinite(n)) throw new Error(`non-finite number ${n}`);
  if (Object.is(n, -0)) return "-0.0";
  let s = String(n);
  if (!/[.e]/.test(s)) s += ".0";
  if (/^-?\d+e/.test(s)) s = s.replace("e", ".0e");
  return s;
}

const rcow = (s) => `Cow::Borrowed(${rstr(s)})`;
const ropt = (v, f) => (v === undefined ? "None" : `Some(${f(v)})`);

function rnum(t) {
  if ("n" in t) return `TNum::N(${rf64(t.n)})`;
  if ("s" in t) return `TNum::S(${rstr(t.s)})`;
  if ("b" in t) return `TNum::B(${t.b})`;
  throw new Error(`bad num ${JSON.stringify(t)}`);
}

const SLOT_NAMES = {
  fillColor: "Fill",
  frameColor: "Frame",
  iconColor: "Icon",
  iconFillColor: "IconFill",
  black: "Black",
  white: "White",
  none: "None",
};
const AFF_NAMES = { self: "SelfAff", Civilian: "Civilian", Friend: "Friend", Hostile: "Hostile", Neutral: "Neutral", Unknown: "Unknown", Suspect: "Suspect" };

function rpaint(p) {
  switch (p.k) {
    case "none":
      return "TPaint::None";
    case "lit":
      return `TPaint::Lit(${rstr(p.v)})`;
    case "mono":
      return "TPaint::Mono";
    case "slot":
      if (!SLOT_NAMES[p.slot] || !AFF_NAMES[p.aff]) throw new Error(`bad slot ${JSON.stringify(p)}`);
      return `TPaint::Slot(Slot::${SLOT_NAMES[p.slot]}, TAff::${AFF_NAMES[p.aff]})`;
  }
  throw new Error(`bad paint ${JSON.stringify(p)}`);
}

function rdash(t) {
  if (t.dash === "pending") return "TDash::Pending";
  if (t.dash === "anticipated") return "TDash::Anticipated";
  return `TDash::Lit(${rstr(t.s)})`;
}

// ---------------------------------------------------------------------------
// Pools.

const styles = [];
const styleIndex = new Map();
function styleOf(t) {
  const s = [
    `fill: ${ropt(t.fill, rpaint)}`,
    `fill_opacity: ${ropt(t.fillopacity, rnum)}`,
    `stroke: ${ropt(t.stroke, rpaint)}`,
    `stroke_width: ${ropt(t.strokewidth, rnum)}`,
    `dash: ${ropt(t.strokedasharray, rdash)}`,
    `line_cap: ${ropt(t.linecap, (v) => rstr(v.s))}`,
    `non_scaling_stroke: ${ropt(t.non_scaling_stroke, rnum)}`,
    `style_fill: ${ropt(t.styleFill, String)}`,
    `icon: ${ropt(t.icon, String)}`,
    `clip_path: ${ropt(t.clipPath, (v) => rstr(v.s))}`,
  ].join(", ");
  const lit = `TStyle { ${s} }`;
  if (!styleIndex.has(lit)) {
    styleIndex.set(lit, styles.length);
    styles.push(lit);
  }
  return styleIndex.get(lit);
}

const texts = [];
const nodes = [];
const nodeIndex = new Map();
const kids = [];
let partIds = null;

function kidsOf(list) {
  const idx = list.map(nodeOf);
  const start = kids.length;
  kids.push(...idx);
  return `Kids { start: ${start}, len: ${idx.length} }`;
}

function nodeOf(t) {
  const key = JSON.stringify(t);
  if (nodeIndex.has(key)) return nodeIndex.get(key);
  let lit;
  if (t.missing) lit = "TNode::Missing";
  else if (t.scalar) lit = `TNode::Scalar(${rnum(t.scalar)})`;
  else if (t.ref !== undefined) lit = `TNode::Ref(${partIds.has(t.ref) ? partIds.get(t.ref) : "UNKNOWN_PART"})`;
  else if (t.group) lit = `TNode::Group(${kidsOf(t.group)})`;
  else {
    const style = styleOf(t);
    const draw = () => kidsOf(t.draw ? (t.draw.group ? t.draw.group : [t.draw]) : []);
    switch (t.type) {
      case "path":
        lit = `TNode::Path { d: ${rstr(t.d ? t.d.s : "")}, style: ${style} }`;
        break;
      case "circle":
        lit = `TNode::Circle { cx: ${rnum(t.cx)}, cy: ${rnum(t.cy)}, r: ${rnum(t.r)}, style: ${style} }`;
        break;
      case "text":
        texts.push(
          `TText { x: ${rnum(t.x)}, y: ${rnum(t.y)}, text: ${rstr(t.text ? t.text.s : "")}, ` +
            `size: ${ropt(t.fontsize, rnum)}, family: ${ropt(t.fontfamily, (v) => rstr(v.s))}, ` +
            `weight: ${ropt(t.fontweight, (v) => rstr(v.s))}, anchor: ${ropt(t.textanchor, (v) => rstr(v.s))}, ` +
            `baseline: ${ropt(t.alignmentBaseline, (v) => rstr(v.s))} }`
        );
        lit = `TNode::Text { text: ${texts.length - 1}, style: ${style} }`;
        break;
      case "translate":
        lit = `TNode::Translate { x: ${rnum(t.x)}, y: ${rnum(t.y)}, kids: ${draw()}, style: ${style} }`;
        break;
      case "rotate":
        lit = `TNode::Rotate { degree: ${rnum(t.degree)}, x: ${rnum(t.x)}, y: ${rnum(t.y)}, kids: ${draw()}, style: ${style} }`;
        break;
      case "scale":
        lit = `TNode::Scale { factor: ${rnum(t.factor)}, kids: ${draw()}, style: ${style} }`;
        break;
      default:
        throw new Error(`bad node ${key.slice(0, 200)}`);
    }
    if (t.draw && !t.draw.group) throw new Error(`non-array draw in ${key.slice(0, 200)}`);
  }
  nodes.push(lit);
  nodeIndex.set(key, nodes.length - 1);
  return nodes.length - 1;
}

const bboxes = [];
const bboxIndex = new Map();
function bboxOf(b) {
  const lit = `[${["x1", "y1", "x2", "y2"].map((k) => ropt(b[k], rf64)).join(", ")}]`;
  if (!bboxIndex.has(lit)) {
    bboxIndex.set(lit, bboxes.length);
    bboxes.push(lit);
  }
  return bboxIndex.get(lit);
}

// Entries: dependency bitmask + mixed-radix row block.
const domainSizes = tables.vars.map((v) => v.domain.length);
const entries = [];
const entryIndex = new Map();
const rows = [];
function entryOf(e) {
  let combos = [[]];
  for (const vi of e.deps) {
    const next = [];
    for (const pre of combos) for (let a = 0; a < domainSizes[vi]; a++) next.push(pre.concat([a]));
    combos = next;
  }
  const byKey = new Map(e.rows);
  const vals = combos.map((combo) => {
    const v = byKey.get(combo.join(","));
    if (v === undefined) throw new Error(`missing row ${combo} for ${e.key}`);
    if (v === "absent") return "ABSENT";
    const t = JSON.parse(v);
    if (t.bbox !== undefined) return t.bbox === null ? "ABSENT" : String(bboxOf(t.bbox));
    return String(nodeOf(t));
  });
  const mask = e.deps.reduce((m, vi) => m | (1 << vi), 0);
  const sig = `${mask}|${vals.join(",")}`;
  if (entryIndex.has(sig)) return entryIndex.get(sig);
  const start = rows.length;
  rows.push(...vals);
  entries.push(`Entry { deps: 0b${mask.toString(2)}, start: ${start} }`);
  entryIndex.set(sig, entries.length - 1);
  return entries.length - 1;
}

const byteCmp = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b));

// Parts first, so references resolve to part indices.
const partEntries = tables.parts.filter((e) => e.key.startsWith("P|"));
const partNames = partEntries.map((e) => e.key.slice(2)).sort(byteCmp);
partIds = new Map(partNames.map((n, i) => [n, i]));
const partByName = new Map(partEntries.map((e) => [e.key.slice(2), e]));
const partList = partNames.map((n) => `(${rstr(n)}, ${entryOf(partByName.get(n))})`);

// Keys look like O|N|15|name or O|L|name.
const overrides = [];
for (const e of tables.parts.filter((e) => e.key.startsWith("O|"))) {
  const parts = e.key.split("|");
  let mapping, name;
  if (parts[1] === "L") {
    mapping = -1;
    name = parts.slice(2).join("|");
  } else {
    mapping = Number(parts[2]);
    name = parts.slice(3).join("|");
  }
  if (!partIds.has(name)) throw new Error(`override of unknown part ${name}`);
  overrides.push(`(${mapping}, ${partIds.get(name)}, ${entryOf(e)})`);
}

const KINDS = ["icons", "m1", "m2", "bbox"];
const number = Array.from({ length: 100 }, () => KINDS.map(() => []));
const letter = { icons: [], bbox: [] };
for (const e of tables.mappings) {
  const parts = e.key.split("|");
  if (parts[0] === "N") {
    const ss = Number(parts[1]);
    const kind = KINDS.indexOf(parts[2]);
    number[ss][kind].push([parts.slice(3).join("|"), entryOf(e)]);
  } else if (parts[0] === "L") {
    letter[parts[1]].push([parts.slice(2).join("|"), entryOf(e)]);
  } else throw new Error(`bad mapping key ${e.key}`);
}
const sortedList = (list) =>
  "&[" + list.sort((a, b) => byteCmp(a[0], b[0])).map(([k, v]) => `(${rstr(k)}, ${v})`).join(", ") + "]";

// ---------------------------------------------------------------------------
// Write files.

function write(name, body) {
  fs.writeFileSync(path.join(genDir, name), HEADER + body);
}
fs.mkdirSync(genDir, { recursive: true });

const affDomain = tables.vars.find((v) => v.name === "affiliation").domain;
const geomDomain = tables.vars.find((v) => v.name === "geometry").domain;
const expectVars = [
  "std2525", "frame", "numberSidc", "alternateMedal", "mono", "edition", "notpresent", "affiliation", "geometry",
  "slot_fillColor", "slot_frameColor", "slot_iconColor", "slot_iconFillColor", "slot_black", "slot_white",
];
if (JSON.stringify(tables.vars.map((v) => v.name)) !== JSON.stringify(expectVars))
  throw new Error("context variable order changed; update template::Var");

write(
  "vars.rs",
  `
use crate::template::VAR_COUNT;

/// Domain size of each context variable, in \`template::Var\` order.
pub(crate) static DOMAIN_SIZES: [u8; VAR_COUNT] = [${domainSizes.join(", ")}];

/// Affiliation domain (values of \`metadata.affiliation\` after upstream's
/// \`|| "Friend"\` fallback).
pub(crate) static AFFILIATIONS: [&str; ${affDomain.length}] = [${affDomain.map(rstr).join(", ")}];

/// Base geometry domain; \`"none"\` is the empty default geometry.
pub(crate) static GEOMETRIES: [&str; ${geomDomain.length}] = [${geomDomain.map(rstr).join(", ")}];
`
);

// The pool is split so no single generated file is unmanageably large.
const CHUNK = 20000;
const nodeChunks = [];
for (let i = 0; i < nodes.length; i += CHUNK) nodeChunks.push(nodes.slice(i, i + CHUNK));
write(
  "pool.rs",
  `
use crate::template::{Kids, TDash, TNode, TNum, TPaint, TStyle, TText, TAff, Slot, UNKNOWN_PART};

/// Template nodes.
pub(crate) static NODES: [TNode; ${nodes.length}] = [
${nodes.map((n) => "    " + n + ",").join("\n")}
];

/// Child lists of group-like nodes, as indices into \`NODES\`.
pub(crate) static KIDS: [u32; ${kids.length}] = [${kids.join(", ")}];

/// Text node payloads.
pub(crate) static TEXTS: [TText; ${texts.length}] = [
${texts.map((n) => "    " + n + ",").join("\n")}
];

/// Presentation attribute sets.
pub(crate) static STYLES: [TStyle; ${styles.length}] = [
${styles.map((n) => "    " + n + ",").join("\n")}
];
`
);
if (nodeChunks.length > 100) throw new Error("pool unexpectedly large");

write(
  "tables.rs",
  `
use crate::template::Entry;
${rows.includes("ABSENT") ? "use crate::template::ABSENT;" : ""}

/// Context-keyed entries: a dependency bitmask and the start of a
/// mixed-radix block in \`ROWS\`.
pub(crate) static ENTRIES: [Entry; ${entries.length}] = [
${entries.map((n) => "    " + n + ",").join("\n")}
];

/// Row values: node indices (or bbox indices for bbox tables), \`ABSENT\`
/// where upstream defines no value in that context.
pub(crate) static ROWS: [u32; ${rows.length}] = [${rows.join(", ")}];

/// Special bounding boxes: \`[x1, y1, x2, y2]\`, \`None\` where upstream leaves
/// the coordinate to the default.
pub(crate) static BBOXES: [[Option<f64>; 4]; ${bboxes.length}] = [
${bboxes.map((n) => "    " + n + ",").join("\n")}
];

/// Icon parts by name (byte-sorted), with their entry index.
pub(crate) static PARTS: [(&str, u32); ${partList.length}] = [
${partList.map((n) => "    " + n + ",").join("\n")}
];

/// Parts mutated in place while a mapping is built (upstream
/// \`ms._scale(…, true)\`): (symbol set or -1 for letter SIDCs, part, entry).
pub(crate) static OVERRIDES: [(i16, u16, u32); ${overrides.length}] = [${overrides.join(", ")}];

/// Number-SIDC mappings: [symbol set][icons, modifier 1, modifier 2, bbox]
/// → byte-sorted (code, entry).
pub(crate) static NUMBER: [[&[(&str, u32)]; 4]; 100] = [
${number.map((kinds) => "    [" + kinds.map(sortedList).join(", ") + "],").join("\n")}
];

/// Letter-SIDC icons by generic SIDC (byte-sorted).
pub(crate) static LETTER_ICONS: &[(&str, u32)] = ${sortedList(letter.icons)};

/// Letter-SIDC special bounding boxes by generic SIDC (byte-sorted).
pub(crate) static LETTER_BBOX: &[(&str, u32)] = ${sortedList(letter.bbox)};

`
);

// Misc tables.
function labelLit(l) {
  for (const k of Object.keys(l))
    if (!["x", "y", "fontsize", "textanchor", "fontweight", "alignmentBaseline", "fill", "stroke"].includes(k))
      throw new Error(`label key ${k}`);
  return (
    `Label { x: ${ropt(l.x, rf64)}, y: ${ropt(l.y, rf64)}, font_size: ${ropt(l.fontsize, rf64)}, ` +
    `anchor: ${ropt(l.textanchor, rcow)}, weight: ${ropt(l.fontweight, rcow)}, ` +
    `baseline: ${ropt(l.alignmentBaseline, rcow)}, fill: ${ropt(l.fill, rcow)}, stroke: ${ropt(l.stroke, String)} }`
  );
}
function labelTable(list) {
  const sorted = list.slice().sort((a, b) => byteCmp(a.sidc, b.sidc));
  return (
    "&[\n" +
    sorted
      .map(
        (e) =>
          `    (${rstr(e.sidc)}, &[${e.fields
            .map((f) => `LabelField { field: ${rcow(f.field)}, is_array: ${f.isArray}, labels: Cow::Borrowed(&[${f.labels.map(labelLit).join(", ")}]) }`)
            .join(", ")}]),`
      )
      .join("\n") +
    "\n]"
  );
}
function geomLit(g) {
  const shape =
    g.g.type === "path"
      ? `GeomShape::Path(${rstr(g.g.d)})`
      : `GeomShape::Circle { cx: ${rf64(g.g.cx)}, cy: ${rf64(g.g.cy)}, r: ${rf64(g.g.r)} }`;
  return `(${rstr(g.name)}, BaseGeometry { shape: ${shape}, bbox: [${rf64(g.bbox.x1)}, ${rf64(g.bbox.y1)}, ${rf64(g.bbox.x2)}, ${rf64(g.bbox.y2)}] })`;
}
const colorVal = (v) => (v === false ? "None" : `Some(${rstr(v)})`);
const COLOR_KEYS = ["Civilian", "Friend", "Hostile", "Neutral", "Unknown", "Suspect"];
write(
  "misc.rs",
  `
use crate::labels::{Label, LabelField};
use alloc::borrow::Cow;
use crate::geometry::{BaseGeometry, GeomShape};

/// Letter-SIDC label overrides by generic SIDC (byte-sorted).
pub(crate) static LETTER_LABELS: &[(&str, &[LabelField])] = ${labelTable(misc.labels.letter)};

/// Number-SIDC label overrides by entity code (byte-sorted).
pub(crate) static NUMBER_LABELS: &[(&str, &[LabelField])] = ${labelTable(misc.labels.number)};

/// Base frame geometries by name.
pub(crate) static GEOMETRIES: [(&str, BaseGeometry); ${misc.geometries.length}] = [
${misc.geometries.map((g) => "    " + geomLit(g) + ",").join("\n")}
];

/// Default colour modes: name → [Civilian, Friend, Hostile, Neutral, Unknown, Suspect].
pub(crate) static COLOR_MODES: [(&str, [Option<&str>; 6]); ${misc.colorModes.length}] = [
${misc.colorModes.map((c) => `    (${rstr(c.name)}, [${COLOR_KEYS.map((k) => colorVal(c.mode[k])).join(", ")}]),`).join("\n")}
];

/// Character widths (at font size 30) by UTF-16 code unit (sorted).
pub(crate) static CHAR_WIDTHS: [(u16, f64); ${misc.charWidths.length}] = [${misc.charWidths.map(([c, w]) => `(${c}, ${rf64(w)})`).join(", ")}];
`
);

console.error(
  `nodes ${nodes.length}, kids ${kids.length}, texts ${texts.length}, styles ${styles.length}, ` +
    `entries ${entries.length}, rows ${rows.length}, bboxes ${bboxes.length}, parts ${partList.length}, overrides ${overrides.length}`
);
