//! Writing the generated modules.

use super::literals::{rcow, rf64, ropt, rstr};
use super::pack::{pack_nodes, pack_rows};
use super::pathcodec::{byte_literal, pack_paths};
use super::{Emitted, Keyed, array};
use crate::Error;
use serde_json::Value;
use std::path::Path;

const HEADER_TAIL: &str = "Regenerate with `tools/codegen/regenerate.sh`; do not edit by hand.\n";

fn header(tables: &Value) -> String {
    let pin = |k: &str| {
        tables
            .get("upstream")
            .and_then(|u| u.get(k))
            .and_then(Value::as_str)
            .unwrap_or("?")
    };
    format!(
        "// @generated by `cargo xtask emit` from milsymbol.js {}\n// ({} @ {}, MIT, see LICENSE-MIT-milsymbol).\n// {HEADER_TAIL}",
        pin("version"),
        pin("upstream"),
        pin("commit"),
    )
}

fn lines(items: &[String]) -> String {
    items
        .iter()
        .map(|n| format!("    {n},"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn sorted_list(list: &Keyed) -> String {
    let mut list = list.clone();
    list.sort_by(|a, b| a.0.as_bytes().cmp(b.0.as_bytes()));
    let items: Vec<String> = list
        .iter()
        .map(|(k, v)| format!("({}, {v})", rstr(k)))
        .collect();
    format!("&[{}]", items.join(", "))
}

fn domain(vars: &[Value], name: &str) -> Vec<String> {
    vars.iter()
        .find(|v| v.get("name").and_then(Value::as_str) == Some(name))
        .and_then(|v| v.get("domain")?.as_array())
        .map(|d| {
            d.iter()
                .map(|x| rstr(x.as_str().unwrap_or_default()))
                .collect()
        })
        .unwrap_or_default()
}

pub(super) fn write_all(
    root: &Path,
    tables: &Value,
    misc: &Value,
    vars: &[Value],
    e: &Emitted,
) -> Result<(), Error> {
    let dir = root.join("src/generated");
    std::fs::create_dir_all(&dir)?;
    let head = header(tables);
    let write = |name: &str, body: String| -> Result<(), Error> {
        let path = dir.join(name);
        std::fs::write(&path, format!("{head}{body}"))
            .map_err(|err| format!("{}: {err}", path.display()).into())
    };
    write("vars.rs", vars_rs(vars, &e.pools.domain_sizes))?;
    write("pool.rs", pool_rs(e)?)?;
    write("tables.rs", tables_rs(e)?)?;
    write("misc.rs", misc_rs(misc)?)
}

fn vars_rs(vars: &[Value], sizes: &[usize]) -> String {
    let (aff, geom) = (domain(vars, "affiliation"), domain(vars, "geometry"));
    let sizes: Vec<String> = sizes.iter().map(ToString::to_string).collect();
    format!(
        "
use crate::template::VAR_COUNT;

/// Domain size of each context variable, in `template::Var` order.
pub(crate) static DOMAIN_SIZES: [u8; VAR_COUNT] = [{}];

/// Affiliation domain (values of `metadata.affiliation` after upstream's
/// `|| \"Friend\"` fallback).
pub(crate) static AFFILIATIONS: [&str; {}] = [{}];

/// Base geometry domain; `\"none\"` is the empty default geometry.
pub(crate) static GEOMETRIES: [&str; {}] = [{}];
",
        sizes.join(", "),
        aff.len(),
        aff.join(", "),
        geom.len(),
        geom.join(", "),
    )
}

fn pool_rs(e: &Emitted) -> Result<String, Error> {
    let p = &e.pools;
    let packed = pack_nodes(p)?;
    let blob = pack_paths(&p.paths)?;
    tracing::info!(
        "paths: {} unique, {} text bytes -> {} packed bytes, {} raw",
        p.paths.len(),
        p.paths.iter().map(String::len).sum::<usize>(),
        blob.bytes.len(),
        blob.raw_paths
    );
    let kids: Vec<String> = p.kids.iter().map(ToString::to_string).collect();
    if p.kids.iter().any(|&k| u16::try_from(k).is_err()) {
        return Err("node index exceeds u16 in KIDS".into());
    }
    Ok(format!(
        "
use crate::template::{{
    Kids, PNode, Slot, T_GROUP, T_PATH, T_REF, T_TEXT, T_WIDE, TAff, TDash, TNode, TNum, TPaint,
    TStyle, TText,
}};

/// Packed template nodes.
pub(crate) static NODES: [PNode; {}] = [
{}
];

/// Nodes too large for a packed record.
pub(crate) static WIDE: [TNode; {}] = [
{}
];

/// Path data of path nodes.
#[cfg(any(test, not(feature = \"compact-paths\")))]
pub(crate) static PATHS: [&str; {}] = [
{}
];

/// Packed path data (see `ir::path::codec`), the paths back to back.
#[cfg(feature = \"compact-paths\")]
pub(crate) static PATH_BYTES: [u8; {}] = *{};

/// Offset of each packed path in `PATH_BYTES`, plus the total length.
#[cfg(feature = \"compact-paths\")]
pub(crate) static PATH_OFFSETS: [u32; {}] = [{}];

/// Child lists of group-like nodes, as indices into `NODES`.
pub(crate) static KIDS: [u16; {}] = [{}];

/// Text node payloads.
pub(crate) static TEXTS: [TText; {}] = [
{}
];

/// Presentation attribute sets.
pub(crate) static STYLES: [TStyle; {}] = [
{}
];
",
        packed.nodes.len(),
        lines(&packed.nodes),
        packed.wide.len(),
        lines(&packed.wide),
        p.paths.len(),
        lines(&p.paths.iter().map(|d| rstr(d)).collect::<Vec<_>>()),
        blob.bytes.len(),
        byte_literal(&blob.bytes),
        blob.offsets.len(),
        blob.offsets
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", "),
        kids.len(),
        kids.join(", "),
        p.texts.len(),
        lines(&p.texts),
        p.styles.len(),
        lines(&p.styles),
    ))
}

fn tables_rs(e: &Emitted) -> Result<String, Error> {
    let p = &e.pools;
    let rows = pack_rows(&p.entries)?;
    let number: Vec<String> = e
        .number
        .iter()
        .map(|kinds| {
            format!(
                "    [{}],",
                kinds.iter().map(sorted_list).collect::<Vec<_>>().join(", ")
            )
        })
        .collect();
    Ok(format!(
        "
use crate::template::Entry;

/// Context-keyed entries: a dependency bitmask and the location of the
/// mixed-radix row block (see `template::Entry`).
pub(crate) static ENTRIES: [Entry; {}] = [
{}
];

/// Row values referenced by bit-packed palette indices: node indices (or
/// bbox indices for bbox tables), `u16::MAX` where upstream defines no value.
pub(crate) static PALETTE: [u16; {}] = [{}];

/// Bit-packed palette indices of the multi-valued entries.
pub(crate) static ROW_DATA: [u8; {}] = [{}];

/// Special bounding boxes: `[x1, y1, x2, y2]`, `None` where upstream leaves
/// the coordinate to the default.
pub(crate) static BBOXES: [[Option<f64>; 4]; {}] = [
{}
];

/// Icon parts by name (byte-sorted), with their entry index.
pub(crate) static PARTS: [(&str, u32); {}] = [
{}
];

/// Part names referenced by the tables but never defined upstream (so only
/// an extension can provide them); `TNode::Ref` indices past `PARTS` point here.
pub(crate) static EXTRA_PART_NAMES: [&str; {}] = [{}];

/// Parts mutated in place while a mapping is built (upstream
/// `ms._scale(…, true)`): (symbol set or -1 for letter SIDCs, part, entry).
pub(crate) static OVERRIDES: [(i16, u16, u32); {}] = [{}];

/// Number-SIDC mappings: [symbol set][icons, modifier 1, modifier 2, bbox]
/// → byte-sorted (code, entry).
pub(crate) static NUMBER: [[&[(&str, u32)]; 4]; 100] = [
{}
];

/// Letter-SIDC icons by generic SIDC (byte-sorted).
pub(crate) static LETTER_ICONS: &[(&str, u32)] = {};

/// Letter-SIDC special bounding boxes by generic SIDC (byte-sorted).
pub(crate) static LETTER_BBOX: &[(&str, u32)] = {};

",
        rows.entries.len(),
        lines(&rows.entries),
        rows.palette.len(),
        join(&rows.palette),
        rows.data.len(),
        join(&rows.data),
        p.bboxes.len(),
        lines(&p.bboxes),
        e.part_list.len(),
        lines(&e.part_list),
        p.extra_names.len(),
        p.extra_names
            .iter()
            .map(|n| rstr(n))
            .collect::<Vec<_>>()
            .join(", "),
        e.overrides.len(),
        e.overrides.join(", "),
        number.join("\n"),
        sorted_list(&e.letter_icons),
        sorted_list(&e.letter_bbox),
    ))
}

fn join<T: ToString>(items: &[T]) -> String {
    items
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(", ")
}

const LABEL_KEYS: [&str; 8] = [
    "x",
    "y",
    "fontsize",
    "textanchor",
    "fontweight",
    "alignmentBaseline",
    "fill",
    "stroke",
];

fn label_literal(l: &Value) -> Result<String, Error> {
    if let Some(bad) = l
        .as_object()
        .and_then(|o| o.keys().find(|k| !LABEL_KEYS.contains(&k.as_str())))
    {
        return Err(format!("label key {bad}").into());
    }
    let cow = |v: &Value| -> Result<String, Error> {
        Ok(rcow(v.as_str().ok_or("label value is not a string")?))
    };
    let flag = |v: &Value| -> Result<String, Error> {
        Ok(v.as_bool()
            .ok_or("label flag is not a boolean")?
            .to_string())
    };
    Ok(format!(
        "Label {{ x: {}, y: {}, font_size: {}, anchor: {}, weight: {}, baseline: {}, fill: {}, stroke: {} }}",
        ropt(l.get("x"), rf64)?,
        ropt(l.get("y"), rf64)?,
        ropt(l.get("fontsize"), rf64)?,
        ropt(l.get("textanchor"), cow)?,
        ropt(l.get("fontweight"), cow)?,
        ropt(l.get("alignmentBaseline"), cow)?,
        ropt(l.get("fill"), cow)?,
        ropt(l.get("stroke"), flag)?,
    ))
}

fn label_field(f: &Value) -> Result<String, Error> {
    let labels = array(f, "labels")?
        .iter()
        .map(label_literal)
        .collect::<Result<Vec<_>, _>>()?;
    Ok(format!(
        "LabelField {{ field: {}, is_array: {}, labels: Cow::Borrowed(&[{}]) }}",
        rcow(f.get("field").and_then(Value::as_str).unwrap_or_default()),
        f.get("isArray").and_then(Value::as_bool).unwrap_or(false),
        labels.join(", "),
    ))
}

fn label_table(list: &[Value]) -> Result<String, Error> {
    let mut sorted: Vec<&Value> = list.iter().collect();
    let sidc = |v: &Value| {
        v.get("sidc")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string()
    };
    sorted.sort_by(|a, b| sidc(a).as_bytes().cmp(sidc(b).as_bytes()));
    let mut rows = Vec::new();
    for e in sorted {
        let fields = array(e, "fields")?
            .iter()
            .map(label_field)
            .collect::<Result<Vec<_>, _>>()?;
        rows.push(format!(
            "    ({}, &[{}]),",
            rstr(&sidc(e)),
            fields.join(", ")
        ));
    }
    Ok(format!("&[\n{}\n]", rows.join("\n")))
}

fn geometry_literal(g: &Value) -> Result<String, Error> {
    let shape = g.get("g").ok_or("geometry without shape")?;
    let num = |v: &Value, k: &str| rf64(v.get(k).unwrap_or(&Value::Null));
    let shape = if shape.get("type").and_then(Value::as_str) == Some("path") {
        format!(
            "GeomShape::Path({})",
            rstr(shape.get("d").and_then(Value::as_str).unwrap_or_default())
        )
    } else {
        format!(
            "GeomShape::Circle {{ cx: {}, cy: {}, r: {} }}",
            num(shape, "cx")?,
            num(shape, "cy")?,
            num(shape, "r")?
        )
    };
    let b = g.get("bbox").ok_or("geometry without bbox")?;
    Ok(format!(
        "({}, BaseGeometry {{ shape: {shape}, bbox: [{}, {}, {}, {}] }})",
        rstr(g.get("name").and_then(Value::as_str).unwrap_or_default()),
        num(b, "x1")?,
        num(b, "y1")?,
        num(b, "x2")?,
        num(b, "y2")?,
    ))
}

const COLOR_KEYS: [&str; 6] = [
    "Civilian", "Friend", "Hostile", "Neutral", "Unknown", "Suspect",
];

fn color_mode_literal(c: &Value) -> String {
    let values: Vec<String> = COLOR_KEYS
        .iter()
        .map(|k| {
            match c
                .get("mode")
                .and_then(|m| m.get(*k))
                .and_then(Value::as_str)
            {
                Some(v) => format!("Some({})", rstr(v)),
                None => String::from("None"),
            }
        })
        .collect();
    format!(
        "    ({}, [{}]),",
        rstr(c.get("name").and_then(Value::as_str).unwrap_or_default()),
        values.join(", ")
    )
}

fn misc_rs(misc: &Value) -> Result<String, Error> {
    let labels = misc.get("labels").ok_or("missing labels")?;
    let geometries = array(misc, "geometries")?
        .iter()
        .map(geometry_literal)
        .collect::<Result<Vec<_>, _>>()?;
    let modes: Vec<String> = array(misc, "colorModes")?
        .iter()
        .map(color_mode_literal)
        .collect();
    let mut widths = Vec::new();
    for w in array(misc, "charWidths")? {
        let unit = w
            .get(0)
            .and_then(Value::as_u64)
            .ok_or("bad char width entry")?;
        widths.push(format!(
            "({unit}, {})",
            rf64(w.get(1).unwrap_or(&Value::Null))?
        ));
    }
    Ok(format!(
        "
use crate::labels::{{Label, LabelField}};
use alloc::borrow::Cow;
use crate::geometry::{{BaseGeometry, GeomShape}};

/// Letter-SIDC label overrides by generic SIDC (byte-sorted).
pub(crate) static LETTER_LABELS: &[(&str, &[LabelField])] = {};

/// Number-SIDC label overrides by entity code (byte-sorted).
pub(crate) static NUMBER_LABELS: &[(&str, &[LabelField])] = {};

/// Base frame geometries by name.
pub(crate) static GEOMETRIES: [(&str, BaseGeometry); {}] = [
{}
];

/// Default colour modes: name → [Civilian, Friend, Hostile, Neutral, Unknown, Suspect].
pub(crate) static COLOR_MODES: [(&str, [Option<&str>; 6]); {}] = [
{}
];

/// Character widths (at font size 30) by UTF-16 code unit (sorted).
pub(crate) static CHAR_WIDTHS: [(u16, f64); {}] = [{}];
",
        label_table(array(labels, "letter")?)?,
        label_table(array(labels, "number")?)?,
        geometries.len(),
        lines(&geometries),
        modes.len(),
        modes.join("\n"),
        widths.len(),
        widths.join(", "),
    ))
}
